DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

DECLARE
    USEREXIST INTEGER;
    USER_NOT_EXIST EXCEPTION;
    PRAGMA EXCEPTION_INIT( USER_NOT_EXIST, -01435 );
BEGIN
SELECT COUNT(*) INTO USEREXIST FROM ALL_USERS WHERE USERNAME='Identity';
IF (USEREXIST = 0) THEN
    RAISE USER_NOT_EXIST;
END IF;
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Identity"."Organization" (
    "Id" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(128) NOT NULL,
    "AddressLine1" NVARCHAR2(128) NOT NULL,
    "AddresssLine2" NVARCHAR2(128) NOT NULL,
    "Email" NVARCHAR2(128) NOT NULL,
    "Phone" NVARCHAR2(16) NOT NULL,
    "LogoUri" NVARCHAR2(256) NOT NULL,
    "Active" NUMBER(1) NOT NULL,
    "Enabled" NUMBER(1) NOT NULL,
    "ActiveUntil" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    "CreatedAt" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    CONSTRAINT "P_Identity_Organization_Id_58009" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Identity"."Platform" (
    "Id" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(128) NOT NULL,
    "Description" NVARCHAR2(512) NOT NULL,
    "SecretKey" NVARCHAR2(128) NOT NULL,
    "LogoUri" NVARCHAR2(256) NOT NULL,
    "Active" NUMBER(1) NOT NULL,
    "Enabled" NUMBER(1) NOT NULL,
    "ActiveUntil" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    "CreatedAt" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    CONSTRAINT "P_Identity_Platform_Id_dffd7" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Identity"."Role" (
    "Id" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(128) NOT NULL,
    "CreatedAt" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    "Active" NUMBER(1) NOT NULL,
    "Enabled" NUMBER(1) NOT NULL,
    "ActiveUntil" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    CONSTRAINT "P_Identity_Role_Id_0808f" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Identity"."User" (
    "Id" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "UniqueId" NVARCHAR2(128) NOT NULL,
    "Username" NVARCHAR2(128) NOT NULL,
    "NormalizedUsername" NVARCHAR2(128) NOT NULL,
    "Password" NVARCHAR2(128) NOT NULL,
    "Email" NVARCHAR2(128) NOT NULL,
    "NormalizedEmail" NVARCHAR2(128) NOT NULL,
    "Phone" NVARCHAR2(16),
    "Mobile" NVARCHAR2(16) NOT NULL,
    "CreatedAt" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    "Enabled" NUMBER(1) NOT NULL,
    "Active" NUMBER(1) NOT NULL,
    "EmailConfirmed" NUMBER(1) NOT NULL,
    "EmailConfirmationCode" NVARCHAR2(2000) NOT NULL,
    "EmailConfirmationDeadline" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    "MobileConfirmed" NUMBER(1) NOT NULL,
    "MobileConfirmationCode" NVARCHAR2(2000) NOT NULL,
    "MobileConfirmationDeadline" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    "LoginFailCount" NUMBER(10) NOT NULL,
    "LockoutUntil" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    CONSTRAINT "P_Identity_User_Id_8d3bc" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Identity"."Permission" (
    "Id" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "UserId" NUMBER(19) NOT NULL,
    "RoleId" NUMBER(19) NOT NULL,
    "OrganizationId" NUMBER(19) NOT NULL,
    "Active" NUMBER(1) NOT NULL,
    "CreatedAt" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    "ActiveUntil" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    "Enabled" NUMBER(1) NOT NULL,
    CONSTRAINT "P_Identity_Permission_Id_a73aa" PRIMARY KEY ("Id"),
    CONSTRAINT "F_Identity_Permission_OrganizationId_abfa1" FOREIGN KEY ("OrganizationId") REFERENCES "Identity"."Organization" ("Id"),
    CONSTRAINT "F_Identity_Permission_RoleId_3b3a4" FOREIGN KEY ("RoleId") REFERENCES "Identity"."Role" ("Id"),
    CONSTRAINT "F_Identity_Permission_UserId_7b5da" FOREIGN KEY ("UserId") REFERENCES "Identity"."User" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Identity"."Session" (
    "Id" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "PlatformId" NUMBER(19) NOT NULL,
    "PermissionId" NUMBER(19) NOT NULL,
    "Jti" NVARCHAR2(128) NOT NULL,
    "TokenHash" NVARCHAR2(128) NOT NULL,
    "RefreshToken" NVARCHAR2(128) NOT NULL,
    "Key" NVARCHAR2(128) NOT NULL,
    "ClientUserAgent" NVARCHAR2(512) NOT NULL,
    "ClientFriendlyName" NVARCHAR2(128) NOT NULL,
    "ClientOS" NVARCHAR2(128) NOT NULL,
    "ClientIP" NVARCHAR2(64) NOT NULL,
    "ClientTimezone" NUMBER(10) NOT NULL,
    "ClientLatitude" DECIMAL(18, 2) NOT NULL,
    "ClientLongitude" DECIMAL(18, 2) NOT NULL,
    "CreatedAt" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    "ExpiresAt" TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    "Revoked" NUMBER(1) NOT NULL,
    CONSTRAINT "P_Identity_Session_Id_c4735" PRIMARY KEY ("Id"),
    CONSTRAINT "F_Identity_Session_PermissionId_16c18" FOREIGN KEY ("PermissionId") REFERENCES "Identity"."Permission" ("Id"),
    CONSTRAINT "F_Identity_Session_PlatformId_45747" FOREIGN KEY ("PlatformId") REFERENCES "Identity"."Platform" ("Id")
)';
END;
/

CREATE UNIQUE INDEX "Identity"."U_Identity_Organization_Name_9b40f" ON "Identity"."Organization" ("Name")
/

CREATE INDEX "Identity"."I_Identity_Permission_OrganizationId_29aa7" ON "Identity"."Permission" ("OrganizationId")
/

CREATE INDEX "Identity"."I_Identity_Permission_RoleId_19e55" ON "Identity"."Permission" ("RoleId")
/

CREATE INDEX "Identity"."I_Identity_Permission_UserId_777e2" ON "Identity"."Permission" ("UserId")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_Permission_UserId_RoleId_OrganizationId_79cd0" ON "Identity"."Permission" ("UserId", "RoleId", "OrganizationId")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_Platform_Name_5a64e" ON "Identity"."Platform" ("Name")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_Platform_SecretKey_0823c" ON "Identity"."Platform" ("SecretKey")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_Role_Name_d6d1e" ON "Identity"."Role" ("Name")
/

CREATE INDEX "Identity"."I_Identity_Session_PermissionId_bd69d" ON "Identity"."Session" ("PermissionId")
/

CREATE INDEX "Identity"."I_Identity_Session_PlatformId_3f620" ON "Identity"."Session" ("PlatformId")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_Session_Jti_2617e" ON "Identity"."Session" ("Jti")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_Session_Key_8e0f1" ON "Identity"."Session" ("Key")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_Session_RefreshToken_16772" ON "Identity"."Session" ("RefreshToken")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_Session_TokenHash_f7bdb" ON "Identity"."Session" ("TokenHash")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_User_Email_aad66" ON "Identity"."User" ("Email")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_User_Mobile_192e6" ON "Identity"."User" ("Mobile")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_User_UniqueId_86495" ON "Identity"."User" ("UniqueId")
/

CREATE UNIQUE INDEX "Identity"."U_Identity_User_Username_66295" ON "Identity"."User" ("Username")
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20210628021601_Migration_Identity1OracleDbContext_1', N'5.0.7')
/

