CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE TABLE "IdentityOrganization" (
        "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
        "Name" character varying(128) NOT NULL,
        "AddressLine1" character varying(128) NOT NULL,
        "AddresssLine2" character varying(128) NOT NULL,
        "Email" character varying(128) NOT NULL,
        "Phone" character varying(16) NOT NULL,
        "LogoUri" character varying(256) NOT NULL,
        "Active" boolean NOT NULL,
        "Enabled" boolean NOT NULL,
        "ActiveUntil" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "P_IdentityOrganization_Id_DBB7E" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE TABLE "IdentityPlatform" (
        "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
        "Name" character varying(128) NOT NULL,
        "Description" character varying(512) NOT NULL,
        "SecretKey" character varying(128) NOT NULL,
        "LogoUri" character varying(256) NOT NULL,
        "Active" boolean NOT NULL,
        "Enabled" boolean NOT NULL,
        "ActiveUntil" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "P_IdentityPlatform_Id_A8230" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE TABLE "IdentityRole" (
        "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
        "Name" character varying(128) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "Active" boolean NOT NULL,
        "Enabled" boolean NOT NULL,
        "ActiveUntil" timestamp with time zone NOT NULL,
        CONSTRAINT "P_IdentityRole_Id_5F896" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE TABLE "IdentityUser" (
        "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
        "UniqueId" character varying(128) NOT NULL,
        "Username" character varying(128) NOT NULL,
        "NormalizedUsername" character varying(128) NOT NULL,
        "Password" character varying(128) NOT NULL,
        "Email" character varying(128) NOT NULL,
        "NormalizedEmail" character varying(128) NOT NULL,
        "Phone" character varying(16) NULL,
        "Mobile" character varying(16) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "Enabled" boolean NOT NULL,
        "Active" boolean NOT NULL,
        "EmailConfirmed" boolean NOT NULL,
        "EmailConfirmationCode" text NOT NULL,
        "EmailConfirmationDeadline" timestamp with time zone NOT NULL,
        "MobileConfirmed" boolean NOT NULL,
        "MobileConfirmationCode" text NOT NULL,
        "MobileConfirmationDeadline" timestamp with time zone NOT NULL,
        "LoginFailCount" integer NOT NULL,
        "LockoutUntil" timestamp with time zone NOT NULL,
        CONSTRAINT "P_IdentityUser_Id_D06A2" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE TABLE "IdentityPermission" (
        "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
        "UserId" bigint NOT NULL,
        "RoleId" bigint NOT NULL,
        "OrganizationId" bigint NOT NULL,
        "Active" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ActiveUntil" timestamp with time zone NOT NULL,
        "Enabled" boolean NOT NULL,
        CONSTRAINT "P_IdentityPermission_Id_AA4E4" PRIMARY KEY ("Id"),
        CONSTRAINT "F_IdentityPermission_OrganizationId_98097" FOREIGN KEY ("OrganizationId") REFERENCES "IdentityOrganization" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "F_IdentityPermission_RoleId_63EA2" FOREIGN KEY ("RoleId") REFERENCES "IdentityRole" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "F_IdentityPermission_UserId_C3DFE" FOREIGN KEY ("UserId") REFERENCES "IdentityUser" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE TABLE "IdentitySession" (
        "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
        "PlatformId" bigint NOT NULL,
        "PermissionId" bigint NOT NULL,
        "Jti" character varying(128) NOT NULL,
        "TokenHash" character varying(128) NOT NULL,
        "RefreshToken" character varying(128) NOT NULL,
        "Key" character varying(128) NOT NULL,
        "ClientUserAgent" character varying(512) NOT NULL,
        "ClientFriendlyName" character varying(128) NOT NULL,
        "ClientOS" character varying(128) NOT NULL,
        "ClientIP" character varying(64) NOT NULL,
        "ClientTimezone" integer NOT NULL,
        "ClientLatitude" numeric NOT NULL,
        "ClientLongitude" numeric NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "Revoked" boolean NOT NULL,
        CONSTRAINT "P_IdentitySession_Id_ECB1D" PRIMARY KEY ("Id"),
        CONSTRAINT "F_IdentitySession_PermissionId_68ABC" FOREIGN KEY ("PermissionId") REFERENCES "IdentityPermission" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "F_IdentitySession_PlatformId_83F1D" FOREIGN KEY ("PlatformId") REFERENCES "IdentityPlatform" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentityOrganization_Name_F13BC" ON "IdentityOrganization" ("Name");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE INDEX "I_IdentityPermission_OrganizationId_EF38A" ON "IdentityPermission" ("OrganizationId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE INDEX "I_IdentityPermission_RoleId_C1B82" ON "IdentityPermission" ("RoleId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE INDEX "I_IdentityPermission_UserId_A10AB" ON "IdentityPermission" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentityPermission_UserId_RoleId_OrganizationId_800D6" ON "IdentityPermission" ("UserId", "RoleId", "OrganizationId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentityPlatform_Name_423B5" ON "IdentityPlatform" ("Name");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentityPlatform_SecretKey_E10BA" ON "IdentityPlatform" ("SecretKey");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentityRole_Name_36689" ON "IdentityRole" ("Name");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE INDEX "I_IdentitySession_PermissionId_EB569" ON "IdentitySession" ("PermissionId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE INDEX "I_IdentitySession_PlatformId_0A8EA" ON "IdentitySession" ("PlatformId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentitySession_Jti_B9210" ON "IdentitySession" ("Jti");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentitySession_Key_45F50" ON "IdentitySession" ("Key");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentitySession_RefreshToken_BC11C" ON "IdentitySession" ("RefreshToken");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentitySession_TokenHash_15499" ON "IdentitySession" ("TokenHash");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentityUser_Email_A5252" ON "IdentityUser" ("Email");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentityUser_Mobile_B52FB" ON "IdentityUser" ("Mobile");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentityUser_UniqueId_E083B" ON "IdentityUser" ("UniqueId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    CREATE UNIQUE INDEX "U_IdentityUser_Username_85643" ON "IdentityUser" ("Username");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210915051308_Migration_IdentityPostgreSqlDbContext_1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210915051308_Migration_IdentityPostgreSqlDbContext_1', '5.0.10');
    END IF;
END $$;
COMMIT;

